# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package Text::Tidx;

use Text::Tidx::SWIG;

sub new {
    my $class = shift;
    my $ref = new Text::Tidx::SWIG::tidx(@_);
    return bless $ref, $class;
}

sub lookup {
    my $self = shift;
    return Text::Tidx::SWIG::tidx::lookup_c($self, @_);
}

sub build {
    return Text::Tidx::SWIG::tidx_build(@_);
}

1;
