#!/bin/bash

# read1, read2
force=
if [[ "$1" == "-f" ]]; then
	shift
	force=1
fi

if [[ "$1" == "-b" ]]; then
        shift
        b=$1
        shift
fi

r1=$1
r2=$2

if [[ "$1" == "-b" ]]; then
	shift
	b=$1
	shift
fi

if [[ -z "$b" ]]; then
	# base filename... remove paired-end and clipped designations
	b=${r1%.gz}
	b=${b%.fastq}
	b=${b%.clipped}
	b=${b%_1}
fi

if [ ! -n "$r2" -o ! -n "$b" ]; then
	echo usage: determine-insert [-b output.prefix] \<read1\> \<read2\>
	exit 1
fi

function onerr {
	# error?  remove everything
	find $b.rfq* -size 0 -exec rm {} + 2> /dev/null
	find $b.insert -size 0 -exec rm {} + 2> /dev/null
	exit 1
}

trap onerr ERR

condor=grun                                       # run in condor
[ -n "$_CONDOR_SLOT" ] && condor="bash -c"              # unless you're already in it

echo Determmine $b 1>&1

set -o xtrace
if [[ ( -n "$force" ) || ( ! -s $b.insert ) || ( $r1 -nt $b.insert ) ]]; then
	[[ $r1 -nt $b.dspec ]] 					&& $condor "determine-species $r1 > $b.dspec"
	[[ $r1 -nt $b.dmol ]] 					&& $condor "determine-molecule $r1 > $b.dmol" &
	[[ $r1 -nt $b.rfq_1 ]] 					&& $condor "randomFQ -c 100000 $r1 $r2 -out $b.rfq"
	wait
	dspec=`cat $b.dspec`

	#if you know the species
	if [ -n "$dspec" ]; then
		refseq=`ea refseq $dspec`

		# probably RNA, and we know the refseq... get a better estimate
		if [ "`cat $b.dmol`" = "RNA" -a -n "$refseq" ]; then
			index=$refseq
		else 
			# ok, try this instead
			index=$dspec
		fi

		if [[ ( -n "$force" ) || ( ! -s $b.rfq.sam ) || ( $r1 -nt $b.rfq.sam ) ]]; then
			$condor "bowtie -e 100 -X 10000 -S --sam-nohead $index -1 $b.rfq_1 -2 $b.rfq_2 > $b.rfq.sam 2> $b.rfq.out"
		fi

		# perl prog
		$condor "/opt/bin/insert-from-sam $b.rfq.sam > $b.insert"
	fi
fi
