/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.05 from the
 * contents of Tidx.xs. Do not edit this file, edit Tidx.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Tidx.xs"
#ifdef __cplusplus
extern "C" {
#endif

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#ifdef __cplusplus
}
#endif

#include "tidx.h"

#line 27 "Tidx.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) __declspec(dllexport) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 169 "Tidx.c"

XS_EUPXS(XS_Text__Tidx_new); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Text__Tidx_new)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "CLASS, path");
    {
	char *	CLASS = (char *)SvPV_nolen(ST(0))
;
	tidx *	RETVAL;
	char *	path = (char *)SvPV_nolen(ST(1))
;

	RETVAL = new tidx(path);
	ST(0) = sv_newmortal();
    sv_setref_pv( ST(0), CLASS, (void*)RETVAL );
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Text__Tidx_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Text__Tidx_DESTROY)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	tidx *	THIS;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
        THIS = (tidx *)SvIV((SV*)SvRV( ST(0) ));
    else{
        warn( "Text::Tidx::DESTROY() -- THIS is not a blessed SV reference" );
        XSRETURN_UNDEF;
    }
;

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Text__Tidx_lookup_c); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Text__Tidx_lookup_c)
{
    dVAR; dXSARGS;
    if (items != 4)
       croak_xs_usage(cv,  "THIS, chr, pos, msep");
    {
	tidx *	THIS;
	const char *	RETVAL;
	dXSTARG;
	const char *	chr = (const char *)SvPV_nolen(ST(1))
;
	int	pos = (int)SvIV(ST(2))
;
	const char *	msep = (const char *)SvPV_nolen(ST(3))
;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
        THIS = (tidx *)SvIV((SV*)SvRV( ST(0) ));
    else{
        warn( "Text::Tidx::lookup_c() -- THIS is not a blessed SV reference" );
        XSRETURN_UNDEF;
    }
;

	RETVAL = THIS->lookup_c(chr, pos, msep);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Text__Tidx_lookup_cr); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Text__Tidx_lookup_cr)
{
    dVAR; dXSARGS;
    if (items != 5)
       croak_xs_usage(cv,  "THIS, chr, beg, end, msep");
    {
	tidx *	THIS;
	const char *	RETVAL;
	dXSTARG;
	const char *	chr = (const char *)SvPV_nolen(ST(1))
;
	int	beg = (int)SvIV(ST(2))
;
	int	end = (int)SvIV(ST(3))
;
	const char *	msep = (const char *)SvPV_nolen(ST(4))
;

    if( sv_isobject(ST(0)) && (SvTYPE(SvRV(ST(0))) == SVt_PVMG) )
        THIS = (tidx *)SvIV((SV*)SvRV( ST(0) ));
    else{
        warn( "Text::Tidx::lookup_cr() -- THIS is not a blessed SV reference" );
        XSRETURN_UNDEF;
    }
;

	RETVAL = THIS->lookup_cr(chr, beg, end, msep);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Text__Tidx_tidx_build); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Text__Tidx_tidx_build)
{
    dVAR; dXSARGS;
    if (items != 8)
       croak_xs_usage(cv,  "file, sep, chr, beg, end, skip_i, skip_c, sub_e");
    {
	const char *	file = (const char *)SvPV_nolen(ST(0))
;
	const char *	sep = (const char *)SvPV_nolen(ST(1))
;
	int	chr = (int)SvIV(ST(2))
;
	int	beg = (int)SvIV(ST(3))
;
	int	end = (int)SvIV(ST(4))
;
	int	skip_i = (int)SvIV(ST(5))
;
	char	skip_c = (char)*SvPV_nolen(ST(6))
;
	bool	sub_e = (bool)SvTRUE(ST(7))
;

	tidx_build(file, sep, chr, beg, end, skip_i, skip_c, sub_e);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Text__Tidx); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Text__Tidx)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Text::Tidx::new", XS_Text__Tidx_new, file);
        newXS("Text::Tidx::DESTROY", XS_Text__Tidx_DESTROY, file);
        newXS("Text::Tidx::lookup_c", XS_Text__Tidx_lookup_c, file);
        newXS("Text::Tidx::lookup_cr", XS_Text__Tidx_lookup_cr, file);
        newXS("Text::Tidx::tidx_build", XS_Text__Tidx_tidx_build, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

